FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-dev

COPY assets ./assets
COPY ui ./ui
COPY src ./src
COPY models ./models
COPY streamlit_app.py .

EXPOSE 8501

CMD [
    "uv",
    "run",
    "streamlit",
    "run",
    "streamlit_app.py",
    "--server.port=8501",
    "--server.address=0.0.0.0"
]